[package]
name = "ap2pmsg"
version = "0.6.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
time = { version = "0.3.30", features = ["serde", "serde-human-readable"]}
serde_json = "1.0.1"
serde = { version = "1.0.189", features = ["derive"] }